name: Main

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  static_analysis:
    name: Run static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.3

      - name: Compute key for CI cache
        run: ./compute_cache_key.sh key.txt

      - name: Setup cache
        uses: actions/cache@v2.1.1
        continue-on-error: true
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Setup gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/githubci-gradle.properties ~/.gradle/gradle.properties

      - name: Run ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run detekt
        uses: DominuS-RU/Detekt-Action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          detekt_config: config/detekt/detekt.yml

      - name: Run android lint
        run: ./gradlew lint --stacktrace

      - name: Post android lint review comments
        uses: dvdandroid/action-android-lint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          lint_xml_file: app/build/reports/lint-results.xml

  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.3

      - name: Compute key for CI cache
        run: ./compute_cache_key.sh key.txt

      - name: Setup cache
        uses: actions/cache@v2.1.1
        continue-on-error: true
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Setup gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/githubci-gradle.properties ~/.gradle/gradle.properties

      - name: Run unit tests and capture code coverage
        run: ./gradlew clean jacocoTestReportDebug --stacktrace

      - name: Collect all test results from all modules
        if: always()
        run: |
          mkdir -p junit
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} junit/ \;

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2.2.0
        with:
          name: junit-results-unit-tests
          path: junit

  assemble_apk:
    name: Assemble apk
    runs-on: ubuntu-latest
    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.3

      - name: Compute key for CI cache
        run: ./compute_cache_key.sh key.txt

      - name: Setup cache
        uses: actions/cache@v2.1.1
        continue-on-error: true
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Setup gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/githubci-gradle.properties ~/.gradle/gradle.properties

      - name: Assemble APK
        run: ./gradlew clean app:assembleDebug --stacktrace

  ui_tests:
    name: Run ui tests
    runs-on: macOS-latest
    needs: assemble_apk
    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.3

      - name: Compute key for CI cache
        run: ./compute_cache_key.sh key.txt

      - name: Setup cache
        uses: actions/cache@v2.1.1
        continue-on-error: true
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Setup gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/githubci-gradle.properties ~/.gradle/gradle.properties

      - name: Run Espresso
        uses: reactivecircus/android-emulator-runner@v2.11.1
        with:
          api-level: 29
          arch: x86_64
          script: ./gradlew clean :app:connectedAndroidTest --stacktrace

      - name: Archive build outputs
        if: always()
        uses: actions/upload-artifact@v2.2.0
        with:
          name: build-outputs
          path: app/build/outputs
