name: Validate PR size
on: [pull_request]

jobs:
  build:
    name: Check PR size
    runs-on: ubuntu-latest
    steps:
      - uses: ookami-kb/gh-pr-size-watcher@v1.4.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          errorSize: 1000
          errorMessage: ':no_entry: PR has more than **{allowed} additions**. Split it into smaller PRs.'
          warningSize: 500
          warningMessage: ':warning: PR has more than **{allowed} additions**. Consider splitting it into smaller PRs.'
          excludePaths:  |
            README.md
            **/*.json
            **/*.xml
            **/*.yml
